### ISSUE TITLE
DirectoryInfo static glob calls fail with unsupported case

### ISSUE THREAD

**Issue by NickJosevski** [kthompson/glob#14]
Testing with what's in the readme.md with some tests results in this runtime error:
```
Expected Tree, found: DirectoryWildcard
   at Glob.Parser.Parse() in C:\nj-dev\glob\src\Glob\Parser.cs:line 216
   at Glob.Glob.Compile() in C:\nj-dev\glob\src\Glob\Glob.cs:line 36
```

The tests:
```
        [Fact]
        public void CanMatchBinFolderGlob()
        {
            var root = new DirectoryInfo(@"C:\");
            var allBinFolders = root.GlobDirectories("**/bin");

            Assert.True(allBinFolders.Any(), "There should be some bin folders");
        }

        [Fact]
        public void CanMatchDllExtension()
        {

            var root = new DirectoryInfo(@"C:\");
            var allDllFiles = root.GlobFiles("**/*.dll");

            Assert.True(allDllFiles.Any(), "There should be some DLL files");
        }

        [Fact]
        public void CanMatchInfoInFileSystemInfo()
        {

            var root = new DirectoryInfo(@"C:\");
            var allInfoFilesAndFolders = root.GlobFileSystemInfos("**/*info");

            Assert.True(allInfoFilesAndFolders.Any(), "There should be some 'allInfoFilesAndFolders'");
        }
```

**Comment by kthompson** [comment]
Closed by PR. Thanks!
