### ISSUE TITLE
GlobDirectories causes ArgumentOutOfRangeException on some inputs.

### ISSUE THREAD

**Issue by alphaleonis** [kthompson/glob#53]
The following code causes an `ArgumentOutOfRangeException`:

`Glob.Directories("C:\\Temp", "**")`

```
Unhandled exception. System.ArgumentOutOfRangeException: Index and count must refer to a location within the string. (Parameter 'count')
   at System.String.Remove(Int32 startIndex, Int32 count)
   at GlobExpressions.Glob.<>c__DisplayClass16_0.<Directories>b__0(DirectoryInfo info)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at TfsGlob.Program.Main(String[] args) in C:\Users\palpet\Source\Repos\TestGlob\TestGlob\Program.cs:line 16
```

This applies to `Glob.FilesAndDirectories` as well.

Adding a trailing backslash to the root directory seems like a workaround for now.

Tested in latest stable (1.1.3) and latest preview (1.1.4-CI-20190706-2) with same results.

**Comment by kthompson** [comment]
@alphaleonis Thanks for the report. I am able to reproduce. I will update the ticket once a new version is available.
