### ISSUE TITLE
Demo page does not work

### ISSUE THREAD

**Issue by rguryanov** [kthompson/glob#83]
https://kthompson.github.io/glob/
Does not work with my setup in chrome\edge\firefox

chrome\edge dev tool console shows:
`
Uncaught TypeError: Cannot read properties of undefined (reading 'dotnet.wasm')
    at blazor.webassembly.js:1:15235
    at l (blazor.webassembly.js:1:22718)
    at <anonymous>:1:20
    at blazor.webassembly.js:1:23616
    at new Promise (<anonymous>)
    at Object.start (blazor.webassembly.js:1:14580)
    at blazor.webassembly.js:1:63775
    at blazor.webassembly.js:1:60646
    at Object.next (blazor.webassembly.js:1:60751)
    at a (blazor.webassembly.js:1:59465)
`
 
 firefox:
 `
 Uncaught TypeError: e.bootConfig.resources.runtime is undefined
    Module https://kthompson.github.io/glob/_framework/blazor.webassembly.js:1
    l https://kthompson.github.io/glob/_framework/blazor.webassembly.js:1
    <anonymous> https://kthompson.github.io/glob/ line 1 > injectedScript:1
    start https://kthompson.github.io/glob/_framework/blazor.webassembly.js:1
    start https://kthompson.github.io/glob/_framework/blazor.webassembly.js:1
    g https://kthompson.github.io/glob/_framework/blazor.webassembly.js:1
    s https://kthompson.github.io/glob/_framework/blazor.webassembly.js:1
    s https://kthompson.github.io/glob/_framework/blazor.webassembly.js:1
    a https://kthompson.github.io/glob/_framework/blazor.webassembly.js:1
    promise callback*u https://kthompson.github.io/glob/_framework/blazor.webassembly.js:1
    a https://kthompson.github.io/glob/_framework/blazor.webassembly.js:1
    promise callback*u https://kthompson.github.io/glob/_framework/blazor.webassembly.js:1
    r https://kthompson.github.io/glob/_framework/blazor.webassembly.js:1
    r https://kthompson.github.io/glob/_framework/blazor.webassembly.js:1
    g https://kthompson.github.io/glob/_framework/blazor.webassembly.js:1
    <anonymous> https://kthompson.github.io/glob/_framework/blazor.webassembly.js:1
    n https://kthompson.github.io/glob/_framework/blazor.webassembly.js:1
    <anonymous> https://kthompson.github.io/glob/_framework/blazor.webassembly.js:1
    <anonymous> https://kthompson.github.io/glob/_framework/blazor.webassembly.js:1
 `
 
 Perhaps it's similar to
 https://github.com/dotnet/aspnetcore/issues/51268

**Comment by kthompson** [comment]
Fixed.
